version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Caminho para o seu Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000  # Adicionado para iniciar o servidor Laravel automaticamente  
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogSphore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge